# Generated by Django 4.2.6 on 2023-12-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_notification_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiring_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
