# Generated by Django 4.2.6 on 2023-12-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_sales_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales_order',
        ),
    ]
