# Generated by Django 4.2.6 on 2023-12-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_delete_sales_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('MP', 'MPESA'), ('VISA', 'VISA'), ('CS', 'CASH'), ('VM', 'VOOMA'), ('BK', 'BANK')], max_length=20, null=True),
        ),
    ]
