# Generated by Django 4.2.6 on 2023-12-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='amount_received',
            field=models.FloatField(blank=True, default=False, null=True),
        ),
    ]
