# Generated by Django 4.2.6 on 2023-12-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0005_alter_sale_amount_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Served by'),
        ),
    ]
