# Generated by Django 4.2.6 on 2023-12-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_billing_cus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='notfy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifications', models.BooleanField(default=False)),
            ],
        ),
    ]
