# Generated by Django 4.2.6 on 2023-12-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_notfy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notfy',
            name='notifications',
        ),
        migrations.AddField(
            model_name='notfy',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
