# Generated by Django 4.2.6 on 2023-12-29 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_remove_notfy_notifications_notfy_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notfy',
        ),
    ]
