# Generated by Django 4.2.6 on 2023-11-01 10:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='item_image',
        ),
        migrations.AddField(
            model_name='invoice',
            name='Qr_code',
            field=models.FileField(default=django.utils.timezone.now, upload_to='item_images/'),
            preserve_default=False,
        ),
    ]
